# Generated by Django 2.2.1 on 2021-03-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='availability',
            field=models.ManyToManyField(blank=True, null=True, related_name='availability', to='users.Availability'),
        ),
    ]
