# Generated by Django 2.2.1 on 2021-03-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210310_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.ForeignKey(on_delete=models.SET('not_active'), to='users.Account', unique=True),
        ),
    ]
