# Generated by Django 2.2.1 on 2021-03-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('staff', models.ForeignKey(on_delete=models.SET('canceled'), to='users.Staff')),
                ('user', models.ForeignKey(on_delete=models.SET('canceled'), to='users.Customer')),
            ],
        ),
    ]
